coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 3%
        threshold: 3
    patch:
      default:
        threshold: 3

comment:
  layout: diff
  require_changes: yes
