/* eslint-disable jsx-quotes */

import React, { Component } from 'react'
import Blob from './Blob'
import c from '../constants'

export default class Issue extends Component {
  render () {
    const { title, body, start, code } = this.props

    if (!title || title === '') {
      return (
        <h1>No issues to create!</h1>
      )
    }

    const Footer = () => [<hr key={1} />, <h6 key={2}>This issue was generated by <a href={c.app}>todo</a> based on a <code>{c.cfg.keyword}</code> comment in <a href="#"><code>{c.sha}</code></a>. It's been assigned to <a href="https://github.com/JasonEtco" className="user-mention">{c.cfg.author}</a> because they committed the code.</h6>]

    return (
      <div className="issue rounded-1">
        <div id="partial-discussion-header" className="gh-header Details">
          <div className="gh-header-show">
            <h1 className="text-normal wb-break-word">
              <span className="issue-title">{title}</span> <span className="issue-number">#129</span>
            </h1>
          </div>
          <div className="TableObject gh-header-meta">
            <div className="TableObject-item">
              <div className="State State--green mr-2">
                <svg aria-hidden="true" className="octicon octicon-issue-opened" height="16" version="1.1" viewBox="0 0 14 16" width="14"><path fillRule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z" /></svg> Open
              </div>
            </div>
            <div className="TableObject-item TableObject-item--primary">
              <a href={c.app} className="author">todo</a><span className="bot-identifier">bot</span> opened this issue just now · 0 comments
            </div>
          </div>
        </div>

        <div className="timeline-comment-wrapper">
          <div className="avatar-parent-child timeline-comment-avatar">
            <a href={c.app}>
              <img alt="@todo" className="avatar rounded-1" height="44" src="https://avatars1.githubusercontent.com/in/5534?v=4&amp;s=88" width="44" />
            </a>
          </div>
          <div className="issue-comment">
            <div className="timeline-comment-header">
              <h3 className="timeline-comment-header-text f5 text-normal">
                <strong><a href={c.app} className="author">todo</a><span className="bot-identifier">bot</span></strong> commented 2 hours ago
              </h3>
            </div>
            <div className="edit-comment-hide">
              <table className="d-block">
                <tbody className="d-block">
                  <tr className="d-block">
                    <td className="d-block comment-body markdown-body">
                      {body && <p>{body}</p>}
                      {body && <hr />}
                      <Blob start={start} code={code} sha={c.sha} />
                      <Footer />
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
