module.exports = `{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ filename }}#{{ range }}

---

{{/if}}
###### This issue was generated by [todo](https://todo.jasonet.co) based on a \`{{ keyword }}\` comment in {{ sha }}.{{ assignedToString }}`
