const {createRobot} = require('probot')
const payloads = require('./fixtures/payloads')
const app = require('..')

function gimmeRobot (config = 'keyword: "@todo"') {
  let robot
  let github
  const content = (str) => Promise.resolve({ data: { content: Buffer.from(str) } })

  robot = createRobot()
  app(robot)

  github = {
    issues: {
      getForRepo: jest.fn().mockReturnValue(Promise.resolve({ data: [{ title: 'An issue that exists', state: 'open' }] })),
      create: jest.fn()
    },
    repos: {
      // Response for getting content from '.github/todo.yml'
      getContent: jest.fn((obj) => {
        if (obj.path.includes('todo.yml')) {
          return content(config)
        } else if (obj.path === 'index.js') {
          return content('\n\n@todo Jason!\nsdfasd\nsdfas\ndsfsa\n\n\nsdfsdaf\n@existing An issue that exists\n\n\n\n')
        } else if (obj.path === 'another.js') {
          return content('\n\n@TODO Another one!\nsdfasd\nsdfas\n\n\n@todo One more issue!\ndsfsa\n\n\nsdfsdaf')
        }
      })
    },
    pullRequests: {
      getAll: jest.fn().mockReturnValue(Promise.resolve({ data: [{ head: { ref: 'master' }, number: 10 }] }))
    }
  }
  // Passes the mocked out GitHub API into out robot instance
  robot.auth = () => Promise.resolve(github)
  return { robot, github }
}

describe('todo', () => {
  it('requests issues for the repo', async () => {
    const {robot, github} = gimmeRobot()
    await robot.receive(payloads.basic)
    expect(github.issues.getForRepo.mock.calls.length).toBe(1)
  })

  it('requests issues for the repo', async () => {
    const {robot, github} = gimmeRobot()
    await robot.receive(payloads.basic)
    expect(github.issues.getForRepo.mock.calls.length).toBe(1)
  })

  it('creates an issue', async () => {
    const {robot, github} = gimmeRobot()
    await robot.receive(payloads.basic)
    expect(github.issues.create.mock.calls.length).toBe(1)
    expect(github.issues.create).toBeCalledWith({
      body: "https://github.com/JasonEtco/test/blob/f7d286aa6381bbb5045288496403d9427b0746e2/index.js#L3-L8\n\n---\n\n###### This issue was generated by [todo](https://github.com/jasonetco/todo) based on a `@todo` comment in f7d286aa6381bbb5045288496403d9427b0746e2 in #10. It's been assigned to @JasonEtco because they committed the code.",
      number: undefined,
      owner: 'JasonEtco',
      repo: 'test',
      title: 'Jason!',
      assignee: 'JasonEtco'
    })
  })

  it('creates an issue without assigning anyone', async () => {
    const {robot, github} = gimmeRobot('autoAssign: false')
    await robot.receive(payloads.basic)
    expect(github.issues.create).toBeCalledWith({
      body: "https://github.com/JasonEtco/test/blob/f7d286aa6381bbb5045288496403d9427b0746e2/index.js#L3-L8\n\n---\n\n###### This issue was generated by [todo](https://github.com/jasonetco/todo) based on a `@todo` comment in f7d286aa6381bbb5045288496403d9427b0746e2 in #10. It's been assigned to @JasonEtco because they committed the code.",
      number: undefined,
      owner: 'JasonEtco',
      repo: 'test',
      title: 'Jason!'
    })
  })

  it('creates an issue and assigns the configured user', async () => {
    const {robot, github} = gimmeRobot('autoAssign: "matchai"')
    await robot.receive(payloads.basic)
    expect(github.issues.create).toBeCalledWith({
      body: "https://github.com/JasonEtco/test/blob/f7d286aa6381bbb5045288496403d9427b0746e2/index.js#L3-L8\n\n---\n\n###### This issue was generated by [todo](https://github.com/jasonetco/todo) based on a `@todo` comment in f7d286aa6381bbb5045288496403d9427b0746e2 in #10. It's been assigned to @JasonEtco because they committed the code.",
      number: undefined,
      owner: 'JasonEtco',
      repo: 'test',
      title: 'Jason!',
      assignee: 'matchai'
    })
  })

  it('creates an issue and assigns the configured users', async () => {
    const {robot, github} = gimmeRobot('autoAssign: ["JasonEtco", "matchai"]')
    await robot.receive(payloads.basic)
    expect(github.issues.create).toBeCalledWith({
      body: "https://github.com/JasonEtco/test/blob/f7d286aa6381bbb5045288496403d9427b0746e2/index.js#L3-L8\n\n---\n\n###### This issue was generated by [todo](https://github.com/jasonetco/todo) based on a `@todo` comment in f7d286aa6381bbb5045288496403d9427b0746e2 in #10. It's been assigned to @JasonEtco because they committed the code.",
      number: undefined,
      owner: 'JasonEtco',
      repo: 'test',
      title: 'Jason!',
      assignees: ['JasonEtco', 'matchai']
    })
  })

  it('works with a complex push (with multiple commits)', async () => {
    const {robot, github} = gimmeRobot()
    await robot.receive(payloads.complex)
    expect(github.issues.create.mock.calls.length).toBe(3)
  })

  it('respects the capitalization config', async () => {
    const {robot, github} = gimmeRobot('keyword: "@TODO"\ncaseSensitive: true')
    await robot.receive(payloads.complex)
    expect(github.issues.create.mock.calls.length).toBe(1)
  })

  it('does not create any issues', async () => {
    const {robot, github} = gimmeRobot('keyword: "pizza"\ncaseSensitive: true')
    await robot.receive(payloads.complex)
    expect(github.issues.create.mock.calls.length).toBe(0)
  })

  it('does not create an issues that already exists', async () => {
    const {robot, github} = gimmeRobot('keyword: "@existing"')
    await robot.receive(payloads.complex)
    expect(github.issues.create.mock.calls.length).toBe(0)
  })
})
